language: c
compiler:
  - clang
  - gcc
env:
  - ARCH=i386 ENABLE_SHARED_EXECUTABLES=YES FALLBACK_U128=NO
  - ARCH=amd64 ENABLE_SHARED_EXECUTABLES=YES FALLBACK_U128=NO
  - ARCH=i386 ENABLE_SHARED_EXECUTABLES=NO FALLBACK_U128=NO
  - ARCH=amd64 ENABLE_SHARED_EXECUTABLES=NO FALLBACK_U128=NO
  - ARCH=i386 ENABLE_SHARED_EXECUTABLES=NO FALLBACK_U128=YES
  - ARCH=amd64 ENABLE_SHARED_EXECUTABLES=NO FALLBACK_U128=YES
os:
  - linux
  # TODO(dcreager): Reenable this once the Travis Mac backlog isn't quite so
  # horrific.
  # - osx
install: .travis/install
script: .travis/test

# In addition to pull requests, always build these branches
branches:
  only:
    - master
